<a href="https://colab.research.google.com/github/chinchu6767/chinchana.lab/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
# Create a Series from a list
data = [1, 3, 5, np.nan, 6]
s = pd.Series(data)
print(s)
#print(type(data[0]))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
dtype: float64


In [3]:
s2 = pd.Series((data), index=['a', 'b', 'c', 'd','e'])
print(s2)

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
dtype: float64


In [6]:
# Create a DataFrame from a dictionary
data = {
    "Name": ["sham", "Robert", "Rahim"],
    "Age": [25, 30, 35],
    "City": ["dubai", "africa", "Delhi"],
}
df = pd.DataFrame(data)
print(df)

     Name  Age    City
0    sham   25   dubai
1  Robert   30  africa
2   Rahim   35   Delhi


In [5]:
print(data.values(), type(data.values()))
print(df.index, type(df.index))

dict_values([['Ram', 'Robert', 'Rahim'], [25, 30, 35], ['Ayodya', 'Chennai', 'Delhi']]) <class 'dict_values'>
RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [7]:
data_x = pd.Series([0, 1, 2, 3, 4, 5])
data_y = pd.Series([0, 1, 4, 9, 16, 25])
df = pd.DataFrame({"x_value": data_x, "square(x)": data_y})
(df)

x_value  square(x)
0        0          0
1        1          1
2        2          4
3        3          9
4        4         16
5        5         25

In [8]:
data_z = pd.Series([0, 1, 8, 27, 64, 125])  # Corrected Series creation
df = pd.DataFrame({"x_value": data_x, "square(x)": data_y, "cube(x)": data_z})
print(df)
print(df.values.shape, type(data.values()))

   x_value  square(x)  cube(x)
0        0          0        0
1        1          1        1
2        2          4        8
3        3          9       27
4        4         16       64
5        5         25      125
(6, 3) <class 'dict_values'>


In [11]:
# Create a DataFrame from a date_range()
dates = pd.date_range("20130101", periods=9)
df_2 = pd.DataFrame(np.random.randn(9, 4), index=dates, columns=list("ABCD"))
print(dates)
print(df_2)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2013-01-01  1.620571 -0.597896 -0.219462 -1.161574
2013-01-02 -0.265478  0.540645  1.642547  0.349893
2013-01-03  1.878111 -0.512786 -0.216596 -0.032779
2013-01-04  0.313024  1.157031  2.195421  0.181535
2013-01-05 -0.034066 -0.619248  0.001981  0.018689
2013-01-06  0.593842  0.447970  1.135427 -1.844670
2013-01-07 -0.539461  0.249242 -2.144512  0.538246
2013-01-08  0.896284  1.058924  1.251207  1.345029
2013-01-09  2.139989  0.743214 -1.802474  0.300145


In [13]:
(df_2.dtypes)

A    float64
B    float64
C    float64
D    float64
dtype: object

In [19]:

data = {
    "Name": ["Ram", "Robert", "Rahim"],
    "Age": [25, 30, 35],
    "City": ["Ayodya", "Chennai", "Delhi"],
}
df = pd.DataFrame(data)

(df)
print("--------")


print("Access a column\n",df["Name"],"\n")

print("Accessing a row by label\n", df.loc[0], "\n")

print("Access a row by index\n", df.iloc[1], "\n")
print("# Access a specific cell\n",df.at[2, "City"],"\n")

print("Slicing",df[1:3])

--------
Access a column
 0       Ram
1    Robert
2     Rahim
Name: Name, dtype: object 

Accessing a row by label
 Name       Ram
Age         25
City    Ayodya
Name: 0, dtype: object 

Access a row by index
 Name     Robert
Age          30
City    Chennai
Name: 1, dtype: object 

# Access a specific cell
 Delhi 

Slicing      Name  Age     City
1  Robert   30  Chennai
2   Rahim   35    Delhi


In [20]:
population_dict = {
    "California": 38332521,
    "Texas": 26448193,
    "Florida": 19552860,
    "Illinois": 12882135,
}
population = pd.Series(population_dict)
print(population_dict, type(population_dict))
print(population, type(population))

{'California': 38332521, 'Texas': 26448193, 'Florida': 19552860, 'Illinois': 12882135} <class 'dict'>
California    38332521
Texas         26448193
Florida       19552860
Illinois      12882135
dtype: int64 <class 'pandas.core.series.Series'>


In [23]:
population['California']
population = pd.Series(population_dict, index=["Texas", "California", "Florida"])
print( population)

Texas         26448193
California    38332521
Florida       19552860
dtype: int64


In [24]:
import numpy as np
A = np.random.randn(5, 3)
print(A, type(A))
dfA = pd.DataFrame(A)
print(dfA,type(dfA))

[[ 0.69409604  1.51610494  1.16279062]
 [ 0.01056992  0.67179577 -0.06897068]
 [ 0.106421    0.645847    0.30068986]
 [ 1.02632484 -1.39537215  0.16414879]
 [-1.4083025   0.60164409  0.04531814]] <class 'numpy.ndarray'>
          0         1         2
0  0.694096  1.516105  1.162791
1  0.010570  0.671796 -0.068971
2  0.106421  0.645847  0.300690
3  1.026325 -1.395372  0.164149
4 -1.408302  0.601644  0.045318 <class 'pandas.core.frame.DataFrame'>


In [25]:
# Filter rows where Age > 25
filtered_df = df[df["Age"] > 25]
print(filtered_df)

     Name  Age     City
1  Robert   30  Chennai
2   Rahim   35    Delhi


In [28]:
print(df[df["Age"]>25])


     Name  Age     City
1  Robert   30  Chennai
2   Rahim   35    Delhi


In [26]:
filtered_df = df[df["Age"].isin([35])]
print(filtered_df)

    Name  Age   City
2  Rahim   35  Delhi


In [31]:
df["Age"].isin

<bound method Series.isin of 0    25
1    30
2    35
Name: Age, dtype: int64>

In [32]:
import pandas as pd
import numpy as np

data = {"A": [1, 2, np.nan, 4], "B": [5, np.nan, 7, 8], "C": [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)

# Drop rows with missing values
df.dropna(inplace=True)  # Modify df directly
print(df)  # Print the modified DataFrame

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN
     A    B    C
0  1.0  5.0  9.0


In [33]:
data = {"A": [1, 2, np.nan, 4], "B": [5, np.nan, 7, 8], "C": [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)

# Fill missing values with 0
df.fillna(0, inplace=True)
print(df)

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN
     A    B     C
0  1.0  5.0   9.0
1  2.0  0.0  10.0
2  0.0  7.0  11.0
3  4.0  8.0   0.0


In [35]:
data = {"A": [1, 2, np.nan, 4], "B": [5, np.nan, 7, 8], "C": [9, 10, 11, np.nan]}
df = pd.DataFrame(data)
print(df)


# Fill missing values with the mean of the column
df["C"].fillna(df["C"].mean(), inplace=True)
(df)

     A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0   NaN


<ipython-input-35-e82d3e5ac199>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["C"].fillna(df["C"].mean(), inplace=True)


A    B     C
0  1.0  5.0   9.0
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0  10.0

In [36]:
data = [10, 12, 13, 11, 12, 14, 10]  # Example dataset without outliers
data_with_outlier = [10, 12, 13, 11, 12, 14, 10, 100]  # Add an extreme outlier


# Calculate mean and median for both cases
mean_without_outlier = np.mean(data)
median_without_outlier = np.median(data)

mean_with_outlier = np.mean(data_with_outlier)
median_with_outlier = np.median(data_with_outlier)

# Print results
print(f"Mean without outlier: {mean_without_outlier:.2f}")
print(f"Median without outlier: {median_without_outlier:.2f}")

print(f"Mean with outlier: {mean_with_outlier:.2f}")
print(f"Median with outlier: {median_with_outlier:.2f}")

Mean without outlier: 11.71
Median without outlier: 12.00
Mean with outlier: 22.75
Median with outlier: 12.00
