<a href="https://colab.research.google.com/github/chinchu6767/chinchana.lab/blob/main/python3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Creating a 1D NumPy array
data1 = [6, 7, 5, 8, 0, 1] #it is a list
arr1 = np.array(data1) # list --> converts to ndarray
print(arr1) # [6 7 5 8 0 1]
print("Type:",type(arr1)) # Type: <class 'numpy.ndarray'>
print("Shape:", arr1.shape) # Shape: (6,)
print("Size:",arr1.size) # Size: 6
print("Dimensions:", arr1.ndim) # Dimensions: 1
print("Data type:", arr1.dtype) # Data type: int64
print("Item_Size:",arr1.itemsize) # size in bytes of each element of the array.
print("total_memory: =", arr1.size * arr1.itemsize,"bytes")

[6 7 5 8 0 1]
Type: <class 'numpy.ndarray'>
Shape: (6,)
Size: 6
Dimensions: 1
Data type: int64
Item_Size: 8
total_memory: = 48 bytes


In [2]:
arr1a = np.array([1,2,3,"RV"])
arr1a
print(arr1a.dtype)
arr1a.itemsize


<U21


84

In [30]:
import numpy as np
# Creating a 2D NumPy array from a list of lists
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print("Dimensions:", arr2.ndim) # Output: 2
print("Shape:", arr2.shape) # Output: (2,4)
print(arr2[1]) # [5,6,7,8]

[[1 2 3 4]
 [5 6 7 8]]
Dimensions: 2
Shape: (2, 4)
[5 6 7 8]


In [4]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# 2D array
d2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# 3D array
d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Shape of 1D array:", d1.shape)
print("Shape of 2D array:", d2.shape)
print("Shape of 3D array:", d3.shape)

Shape of 1D array: (12,)
Shape of 2D array: (4, 3)
Shape of 3D array: (2, 2, 3)


In [5]:
np.ones()


TypeError: ones() missing 1 required positional argument: 'shape'

In [26]:
array1 = np.array([[0, 1, 2], [2, 3, 4]]) # Manual creation
array2 = np.array( [ [1,2], [3,4] ], dtype=float) # Specifying data type
array3 = np.zeros((2, 3)) # Array of zeros
array4 = np.ones((2, 6)) # Array of ones
array5 = np.eye(3) # Identity matrix
array6 = np.arange(0, 10, 2) # Sequence from 0 to 8 with step 2
array7 = np.linspace(4, 10, 5) # create 5 elements in between 0 to 10 with equal space
array8 = np.random.randint(0, 10, (6, 3)) # Random integers in a 3x3 array
print(array1, "\n")
print(array2, "\n")
print(array3, "\n")
print(array4, "\n")
print(array5, "\n")
print(array6, "\n")
print(array7, "\n")
print(array8, "\n")

[[0 1 2]
 [2 3 4]] 

[[1. 2.]
 [3. 4.]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[0 2 4 6 8] 

[ 4.   5.5  7.   8.5 10. ] 

[[6 5 1]
 [2 8 8]
 [6 2 4]
 [5 7 3]
 [5 8 3]
 [8 5 1]] 



In [24]:
random_array = np.random.randint(1,27,5)
print(random_array)

[ 1 20 22 20 12]


In [8]:
random_array = np.random.random((6,5))
print(random_array)

[[0.26640534 0.57349389 0.311512   0.53466524 0.09921188]
 [0.38930152 0.89132866 0.20466838 0.8907601  0.69149028]]


In [23]:

np.random.seed(seed=13)
random_array = np.random.random((2,6))
print(random_array)

[[0.77770241 0.23754122 0.82427853 0.9657492  0.97260111 0.45344925]
 [0.60904246 0.77552651 0.64161334 0.72201823 0.03503652 0.29844947]]


In [22]:
import numpy as np
arr = np.arange(10)
print("Original array:", arr)
print("Element at index 5:", arr[4])
print("Slice from index 5 to 8:", arr[4:8])
arr[5:8] = 19
print("Modified array:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Element at index 5: 4
Slice from index 5 to 8: [4 5 6 7]
Modified array: [ 0  1  2  3  4 19 19 19  8  9]


In [21]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Original array:", arr_2d)
print("Original array:", arr_2d.ndim)
print("Element at index 0:", arr_2d[0])
print("Slice from index at 0 form 1 to 3:", arr_2d[0,1:3])
arr_2d[1, 1] = 18
print("Modified array:", arr_2d)

Original array: [[1 2 3]
 [4 5 6]]
Original array: 2
Element at index 0: [1 2 3]
Slice from index at 0 form 1 to 3: [2 3]
Modified array: [[ 1  2  3]
 [ 4 18  6]]


In [20]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original Array:\n", arr)

# Slice the first row
row_slice = arr[0, :]  # Equivalent to arr[0]

# Slice the second column
col_slice = arr[:, -1]

# Slice a submatrix (rows 1-2, columns 2-3)
submatrix = arr[0:5 ,5:4]

print("\nFirst Row:", row_slice)
print("Second Column:", col_slice)
print("Submatrix:\n", submatrix)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row: [1 2 3 4]
Second Column: [ 4  8 12]
Submatrix:
 []


In [17]:
import numpy as np

# Create a 2D array
arr = np.array([[13, 2, 53, 4],
                [5, 6, 97, 8],
                [9, 10, 141, 12]])

# Slice every second row and column
sliced_arr = arr[::2, ::2]

print("Sliced Array with Steps:\n", sliced_arr)

Sliced Array with Steps:
 [[ 13  53]
 [  9 141]]


In [15]:
arr_3 = np.array([[4., 2., 38], [4., 52., 65.], [7., 8., 97.], [1., 36., 52.]])
arr_tranp = arr_3.transpose()
print("Original matrix:\n", arr_3)
print("Transpose matrix:\n", arr_tranp)

Original matrix:
 [[ 4.  2. 38.]
 [ 4. 52. 65.]
 [ 7.  8. 97.]
 [ 1. 36. 52.]]
Transpose matrix:
 [[ 4.  4.  7.  1.]
 [ 2. 52.  8. 36.]
 [38. 65. 97. 52.]]


In [31]:
arr = np.array([5, 2, 8, 1, 3])
arr2D = np.array([[3, 2, 1], [6, 5, 4]])
# Sorting in ascending order (default)
sorted_arr = np.sort(arr)
print(sorted_arr) # Output: [1 2 3 5 8]
# Sorting in descending order
sorted_desc = np.sort(arr)[::-1]
print(sorted_desc) # Output: [8 5 3 2 1]
# Sort each row
sorted_rows = np.sort(arr2D, axis=0) # [[1 2 3]
print(sorted_rows) # [4 5 6]]
# Sort each row # Output:
sorted_cols = np.sort(arr2D, axis=1) # [[3 2 1]
print(sorted_cols) # [6 5 4]]

[1 2 3 5 8]
[8 5 3 2 1]
[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]


In [32]:
# Create a 1D array with 12 elements
arr = np.arange(24) # [0, 1, 2, ..., 11]
# Reshape into a 3x4 array
reshaped_arr = arr.reshape(6, 4)
print("Original Array (1D):\n", arr)
print("Reshaped Array (3x4):\n", reshaped_arr)
# Reshape into a 2x3x4 array (2 layers, 3 rows, 4 columns)
reshaped_arr_3D = arr.reshape(2, 3, 4)
print("Reshaped Array (2x3x4):\n", reshaped_arr_3D)

Original Array (1D):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Reshaped Array (2x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
import numpy as np

# Create a row matrix (1D array)
row_matrix = np.array([1, 2, 3, 4])

# Reshape into a column matrix (2D array with shape (4, 1))
column_matrix = row_matrix.reshape(-1, 1)

print("Row Matrix:\n", row_matrix)
print("Column Matrix:\n", column_matrix)

Row Matrix:
 [1 2 3 4]
Column Matrix:
 [[1]
 [2]
 [3]
 [4]]


In [37]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("Element-wise addition:\n", arr + 2)
print("Element-wise multiplication:\n", arr * 2)
print("Element-wise exponentiation:\n", arr ** 2)
print("Comparison:\n", arr2 > arr)

Element-wise addition:
 [[3. 4. 5.]
 [6. 7. 8.]]
Element-wise multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]]
Element-wise exponentiation:
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Comparison:
 [[False  True False]
 [ True False  True]]


In [35]:
arr_1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr_2 = np.array([[7., 8., 9.], [1., 3., 5.]])
print("Original array:\n", arr_1, arr_2)
print("Element-wise addition:\n", arr_1 + arr_2)
print("Element-wise subtraction:\n", arr_1 - arr_2)
print("Element-wise multiplication:\n", arr_1 * arr_2) # np.multiply(arr_1,arr_2)


Original array:
 [[1. 2. 3.]
 [4. 5. 6.]] [[7. 8. 9.]
 [1. 3. 5.]]
Element-wise addition:
 [[ 8. 10. 12.]
 [ 5.  8. 11.]]
Element-wise subtraction:
 [[-6. -6. -6.]
 [ 3.  2.  1.]]
Element-wise multiplication:
 [[ 7. 16. 27.]
 [ 4. 15. 30.]]
